# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0002_auto_20190512_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='max_atmosphering_speed',
            field=models.CharField(max_length=255),
        ),
    ]
