# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0003_auto_20190512_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='cost_in_credits',
            field=models.CharField(max_length=255),
        ),
    ]
